package mapgen

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
)

// ErrNotImplemented is returned by Backfill in this slice. Backfill is fully
// wired in Slice 4 of the obsidian-vault-specs change.
var ErrNotImplemented = errors.New("mapgen: Backfill is not yet implemented")

// defaultMap is the seed content used when openspec/map.md does not exist.
const defaultMap = `# openspec Map

This is the vault's entry node: a generated overview of every capability under
` + "`specs/`" + ` and every change under ` + "`changes/`" + `, with backlinks between them. The
managed region below is regenerated by ` + "`archon map`" + ` and MUST NOT be hand-edited;
this preamble is authored prose and is preserved across every regeneration. See
` + "`skills/_shared/spec-vault.md`" + ` for the full vault convention.

` + mapStart + "\n" + mapEnd + "\n"

// Generate regenerates the managed region of {root}/openspec/map.md from a
// fresh scan of {root}/openspec. It creates map.md with the default preamble
// if the file is absent, and preserves all authored content outside the
// markers. Writes are atomic (temp file + rename).
func Generate(root string) error {
	openspecDir := filepath.Join(root, "openspec")
	mapPath := filepath.Join(openspecDir, "map.md")

	existing := defaultMap
	if data, err := os.ReadFile(mapPath); err == nil {
		existing = string(data)
	} else if !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("read map.md: %w", err)
	}

	g, err := Scan(os.DirFS(openspecDir))
	if err != nil {
		return fmt.Errorf("scan openspec: %w", err)
	}

	updated, err := Splice(existing, Render(g))
	if err != nil {
		return fmt.Errorf("splice map.md: %w", err)
	}

	tmp := mapPath + ".tmp"
	if err := os.WriteFile(tmp, []byte(updated), 0o644); err != nil {
		return fmt.Errorf("write map.md: %w", err)
	}
	if err := os.Rename(tmp, mapPath); err != nil {
		return fmt.Errorf("rename map.md: %w", err)
	}
	return nil
}

// Backfill will rewrite boundary-crossing relative links in every archived
// change and regenerate map.md. Not implemented in this slice — see
// ErrNotImplemented.
func Backfill(root string) error {
	return ErrNotImplemented
}
