package mapgen

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"regexp"
)

// archiveDirRe matches an archived change directory name: a YYYY-MM-DD date
// prefix followed by the change name, e.g. "2026-01-01-my-feature".
var archiveDirRe = regexp.MustCompile(`^\d{4}-\d{2}-\d{2}-(.+)$`)

// defaultMap is the seed content used when openspec/map.md does not exist.
const defaultMap = `# openspec Map

This is the vault's entry node: a generated overview of every capability under
` + "`specs/`" + ` and every change under ` + "`changes/`" + `, with backlinks between them. The
managed region below is regenerated by ` + "`archon map`" + ` and MUST NOT be hand-edited;
this preamble is authored prose and is preserved across every regeneration. See
` + "`skills/_shared/spec-vault.md`" + ` for the full vault convention.

` + mapStart + "\n" + mapEnd + "\n"

// Generate regenerates the managed region of {root}/openspec/map.md from a
// fresh scan of {root}/openspec. It creates map.md with the default preamble
// if the file is absent, and preserves all authored content outside the
// markers. Writes are atomic (temp file + rename).
func Generate(root string) error {
	openspecDir := filepath.Join(root, "openspec")
	mapPath := filepath.Join(openspecDir, "map.md")

	existing := defaultMap
	if data, err := os.ReadFile(mapPath); err == nil {
		existing = string(data)
	} else if !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("read map.md: %w", err)
	}

	g, err := Scan(os.DirFS(openspecDir))
	if err != nil {
		return fmt.Errorf("scan openspec: %w", err)
	}

	updated, err := Splice(existing, Render(g))
	if err != nil {
		return fmt.Errorf("splice map.md: %w", err)
	}

	tmp := mapPath + ".tmp"
	if err := os.WriteFile(tmp, []byte(updated), 0o644); err != nil {
		return fmt.Errorf("write map.md: %w", err)
	}
	if err := os.Rename(tmp, mapPath); err != nil {
		return fmt.Errorf("rename map.md: %w", err)
	}
	return nil
}

// Backfill rewrites boundary-crossing relative links in every archived
// change (treating its archive path as current and changes/{name}/ as the
// pre-archive path), then regenerates map.md. Idempotent: a second run over
// already-correct files produces zero diff (RewriteMove no-ops once every
// link already resolves).
func Backfill(root string) error {
	names, err := ArchivedChangeNames(root)
	if err != nil {
		return fmt.Errorf("list archived changes: %w", err)
	}

	for _, name := range names {
		oldRel := path.Join("changes", name.Name)
		newRel := path.Join("changes", "archive", name.Dir)
		if err := RewriteMove(root, oldRel, newRel); err != nil {
			return fmt.Errorf("rewrite links for %s: %w", name.Dir, err)
		}
	}

	return Generate(root)
}

// ArchivedChange pairs an archive directory entry with the change name
// parsed out of its YYYY-MM-DD-{name} prefix.
type ArchivedChange struct {
	Dir  string // e.g. "2026-01-01-my-feature"
	Name string // e.g. "my-feature"
}

// ArchivedChangeNames lists every entry under
// {root}/openspec/changes/archive/ matching the date-prefixed convention.
// Returns nil (no error) if the archive directory does not exist. Shared by
// Backfill and by `archon map --backfill`'s per-change progress reporting.
func ArchivedChangeNames(root string) ([]ArchivedChange, error) {
	entries, err := os.ReadDir(filepath.Join(root, "openspec", "changes", "archive"))
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, nil
		}
		return nil, err
	}

	var changes []ArchivedChange
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		if m := archiveDirRe.FindStringSubmatch(entry.Name()); m != nil {
			changes = append(changes, ArchivedChange{Dir: entry.Name(), Name: m[1]})
		}
	}
	return changes, nil
}
