Feature: archon map CLI and Go module
  The archon map command deterministically regenerates map.md, rewrites boundary-crossing
  links on archive, guards integrity via --check, and supports one-shot backfill.

  @happy
  Scenario: map.md index sections are generated
    Given an openspec/ tree with two capabilities and one active change
    When archon map is run
    Then map.md contains a capabilities index listing both capabilities
    And an active-changes index listing the active change with its phase and status
    And an archive index (empty if no archived changes)
    And a backlink section associating each capability with changes that reference it

  @happy
  Scenario: Generation is deterministic and idempotent
    Given openspec/map.md generated by a first run of archon map
    When archon map is run a second time without any file changes
    Then the resulting map.md is byte-identical to the first run output

  @happy
  Scenario: Active change phase and status come from state.yaml
    Given changes/my-feature/state.yaml with phase: design and status: in_progress
    When archon map is run
    Then the active-changes index shows my-feature with phase=design and status=in_progress

  @happy
  Scenario: Existing prose outside markers is preserved
    Given openspec/map.md with authored prose before and after the managed region
    When archon map is run
    Then prose outside the markers is byte-identical to before
    And only content inside the markers is replaced

  @edge
  Scenario: map.md created when absent
    Given openspec/ exists but map.md does not
    When archon map is run
    Then openspec/map.md is created
    And it contains a managed region with the generated index and backlinks

  @happy
  Scenario: Check passes when map.md is up to date
    Given openspec/map.md freshly generated and no dangling relative links
    When archon map --check is run
    Then the command exits zero
    And no errors are reported

  @error
  Scenario: Check fails on stale managed region
    Given openspec/map.md whose managed region does not match a fresh generation
    When archon map --check is run
    Then the command exits non-zero
    And the output identifies the stale managed region
    And no files are modified

  @error
  Scenario: Check fails on dangling relative link
    Given an openspec artifact containing a relative link to a file that does not exist
    When archon map --check is run
    Then the command exits non-zero
    And the output identifies the dangling link and the source file
    And no files are modified

  @happy
  Scenario: map.md link to change is updated after archive move
    Given map.md containing a relative link to changes/my-feature/proposal.md
    When sdd-archive moves my-feature to changes/archive/2026-07-22-my-feature/
    Then map.md is updated to link to changes/archive/2026-07-22-my-feature/proposal.md
    And no other links in map.md are modified

  @happy
  Scenario: Intra-change relative links to specs/ are rewritten after move
    Given a change artifact containing a relative link ../../../specs/foo/spec.md
    When the change is moved one directory deeper into the archive
    Then the relative link is rewritten to ../../../../specs/foo/spec.md
    And the link resolves to the same target file as before

  @happy
  Scenario: Wikilinks are not rewritten during archive
    Given a change artifact containing [[harness-workflow]]
    When the change is archived
    Then the wikilink is not modified

  @happy
  Scenario: Backfill rewrites links in existing archived changes
    Given archived changes containing relative links that cross the archive boundary
    When archon map --backfill is run
    Then all boundary-crossing relative links in archived changes are rewritten
    And archon map --check passes after backfill completes

  @happy
  Scenario: Backfill is idempotent
    Given archived changes already processed by a first --backfill run
    When archon map --backfill is run a second time
    Then no files are modified (output is identical to the prior run)

  @edge
  Scenario: Default run does not touch archived changes
    Given archived changes with stale links
    When archon map is run without --backfill
    Then no archived change files are modified
